ROOT='/work/egrassi'
HROOT='/home/egrassi'
PRJ_ROOT='/work/egrassi/WXS'
SRC_DIR=PRJ_ROOT+'/local/src'
BIN_DIR=PRJ_ROOT+'/local/bin'
DATA_DIR=PRJ_ROOT+'/local/share/data'
DEBUG="yes"

## This dataset:
#DATA=DATA_DIR+'/spatial'
DATA=PRJ_ROOT+"/local/share/data/MA_qc_biodiversa"
FQ_DIR=PRJ_ROOT+'/dataset/MA_qc_biodiversa'
FQ_XENOME_DIR=FQ_DIR+"/xenome"
FQ_TRIM_DIR=FQ_DIR+"/trim"
# EMPTY for WGS
EXONS=""
LSEXONS=""
SEXONS=""
#[data]egrassi@hactarlogin$ ls *1.fastq.gz | perl -ane '/(CRC[0-9A-Z]+)/; print "\"$1\"",';
#SAMPLES=["CRC0542LMX0B01001TUMD11000","CRC0542LMX0B02001TUMD02000","CRC0542LMX0B02003TUMD02000","CRC0542LMX0B03020TUMD05000","CRC0542LMX0B04006TUMD02000"]
SAMPLES_ORIG=["1740D-84-01_S48_L004","1740D-84-02_S52_L005"]
SAMPLES=["CRC1307NLH","CRC1307LMO"]
REF=SAMPLES[0]
SAMPLESD=SAMPLES[1:len(SAMPLES)]
SAMPS=",".join(SAMPLESD)


#XENOMED_SAMPLES=["CRC1307NLH"] # just an example
XENOMED_SAMPLES=""
# normal liver, organoide bulk basale
FASTQ_SUFFIX="_{pair}.fastq.gz"
FASTQ_SUFFIX_XENOME="_human_{pair}.fastq"
#XENOME_FQ_DIR=""
DBSNP=PRJ_ROOT+"/dataset/spatial/dbsnp.all.vcf.gz"

PAIRS=['R1_001','R2_001']
PAIRS_XENOME=PAIRS
CORES=16
MEM=4
# TODO need to adapt to unpaired (do they exists?) reads, will need to change the all rule in the subdirs using an input function...
PATTERNED=2500 
# HiSeq4000  and Novaseq 6000, otherwise 100 for unpatterned
#–o recal.bam
# TODO
LOWERAF="0.0000025"

wildcard_constraints:
    sample="[a-zA-Z0-9]+"

# Used references
#https://gdc.cancer.gov/about-data/data-harmonization-and-generation/gdc-reference-files based on
#ftp://ftp.ncbi.nlm.nih.gov/genomes/archive/old_genbank/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines/README_ANALYSIS_SETS
# DBSNP 151 ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/All_20180418.vcf.gz
ANNOTATIONS=HROOT+"/common/task/annotations/dataset/gdc"

CALLABLE="5:10,10:50,50:100,100:150,150:inf"
CALLABLE_STRICT="50:100,100:150,150:inf"

MINDP=10

#GNOMAD=ROOT+"/common/task/annotations/dataset/gnomad"
GNOMAD=PRJ_ROOT+"/local/share/data"
VEP_CACHE_DIR=HROOT+"/common/task/variant_annotations/dataset/VEP"
REFFLAT="../refFlat.txt"
REFFLATGZ=HROOT+"/common/task/annotations/dataset/ucsc/hg38/refFlat.txt.gz"

# Singularity containers
GATK_SING=ROOT+"/gatk4100/gatk.img"

rule all_something:
    input: expand("{sample}-"+REF+".{{something}}", sample=SAMPLESD)
    output: "all_samples_{something}"
    shell: "touch {output}"

rule all_single_something:
    input: expand("{sample}.{{something}}", sample=SAMPLES)
    output: "all_samples_{something}"
    shell: "touch {output}"
